In [1]:
import numpy as np
import matplotlib.pyplot as plt
import corner

In [2]:
T = 0.733  # observation time (years)
dt = 5.0  # time step (seconds)
M = 507236.8057121273 * 1.2  # large mass (solar)
a = 0.6  # spin / will be ignored in Schwarzschild waveform
mu = 18.063091389346287  # small mass (solar)
p0 = 10.752251937834985  # initial separation
e0 = 0.3857270761433499  # initial eccentricity
x0 = 0.7  # initial cosine of the inclination / will be ignored in Schwarzschild waveform
qK = np.pi / 2 - 0.6275167236796371  # polar spin angle
phiK = 1.7262549907689677  # azimuthal viewing angle
qS = 2.17583780178878  # polar sky angle
phiS = 0.7101021513597163  # azimuthal viewing angle
dist = 1.4357198958825074 / 2  # distance
Phi_phi0 = 0  # initial phase in phi
Phi_theta0 = 1.7262549907689677  # initial phase in theta
Phi_r0 = 0  # initial phase in r

In [5]:
true_point = np.array([M, mu, a, p0, e0, x0, dist, np.cos(qS), phiS, np.cos(qK), phiK])

In [4]:
chn_sangria = np.load("../chain_files/with_sangria/20000_iter/chain_0.npy")

In [8]:
max_likelihood = chn_sangria[np.argmax(chn_sangria[:, -1]), :-1]
experimental_delta_theta = max_likelihood - true_point

In [10]:
Gamma_matrix = np.load("save_files/Gamma_matrix.npy")
term_2 = np.load("save_files/term_2.npy") # = (d_i h, delta H)
estimated_delta_theta = np.linalg.inv(Gamma_matrix) @ term_2

In [11]:
sigma = np.sqrt(np.diag(np.linalg.inv(Gamma_matrix)))

# Comparing experimental $\Delta\theta$, estimated $\Delta\theta$ and sigma

In [13]:
np.abs(experimental_delta_theta / sigma)

array([2.25929731, 5.96749259, 0.71802399, 5.99933751, 0.41607791,
       2.61364492, 1.34272744, 2.13709845, 3.77781443, 1.50373763,
       0.59755146])

In [14]:
np.abs(estimated_delta_theta / sigma)

array([0.07945408, 0.57598766, 2.81596221, 1.23627485, 2.10004446,
       0.02039447, 1.29251286, 1.03776104, 0.41507978, 1.32351056,
       0.64169758])

In [17]:
np.abs(estimated_delta_theta / experimental_delta_theta)

array([0.03516761, 0.09652088, 3.92182191, 0.20606856, 5.0472385 ,
       0.00780307, 0.96260255, 0.48559346, 0.10987299, 0.88014727,
       1.07387835])